#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agendav"
name = "AgenDAV"
description.en = "CalDAV web client"
description.fr = "Client web pour CalDAV"

version = "2.6.0~ynh3"

maintainers = []

[upstream]
license = "GPL-3.0"
code = "https://github.com/agendav/agendav"
demo = "https://demo.yunohost.org/agendav"
admindoc = "https://agendav.readthedocs.io"
# fund = "???"

[integration]
yunohost = ">= 11.1.0"
architectures = "all"
multi_instance = false
ldap = true
sso = true
disk = "10M"
ram.build = "50M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agendav"

    [install.init_main_permission]
    help.en = "A public server means that everybody is able to access to the main page of the forge, on the public profile of the user and on the public repository. But you still can limit the access to each repository if you set it as private. Note that to be able to use the remote Git command (clone, pull, push) with HTTP and to use the API by (by example with a smartphone), you need to set this application as public."
    help.fr = "Un serveur public signifie que tout le monde peut accéder à la page principale de la forge, au profil public des utilisateurs et aux dépôts publics. Vous pouvez également définir les dépôts comme étant privés. Notez que pour pouvoir utiliser les commandes Git distantes (clone, pull, push) avec HTTP et pour pouvoir utiliser l'API (par exemple avec un smartphone), vous devez paramétrer cette application comme étant publique."
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de_DE", "en", "es_ES", "fr_FR", "it_IT", "nl_NL"]
    default = "en"

[resources]
    [resources.sources.main]
    url = "https://github.com/agendav/agendav/releases/download/2.6.0/agendav-2.6.0.tar.gz"
    sha256 = "af72c07886e30d2443ce9587992f59c78fad5ab4a069e311286e1e7216db895e"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-ctype",
        "php7.4-curl",
        "php7.4-mbstring",
        "php7.4-mcrypt",
        "php7.4-tokenizer",
        "php7.4-xml",
        "php7.4-xmlreader",
        "php7.4-xmlwriter",
        "php7.4-mysql",
        "mariadb-server"
    ]

    [resources.database]
    type = "mysql"
