#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agendav"
name = "AgenDAV"
description.en = "CalDAV web client"
description.fr = "Client web pour CalDAV"

version = "2.6.0~ynh3"

maintainers = []

[upstream]
license = "GPL-3.0"
code = "https://github.com/agendav/agendav"
demo = "https://demo.yunohost.org/agendav"
admindoc = "https://agendav.readthedocs.io"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "10M"
ram.build = "100M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agendav"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de_DE", "en", "es_ES", "fr_FR", "it_IT", "nl_NL"]
    default = "en"

[resources]
    [resources.sources.main]
    url = "https://github.com/agendav/agendav/releases/download/2.6.0/agendav-2.6.0.tar.gz"
    sha256 = "af72c07886e30d2443ce9587992f59c78fad5ab4a069e311286e1e7216db895e"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php7.4-ctype, php7.4-curl, php7.4-mbstring, php7.4-mcrypt, php7.4-tokenizer, php7.4-xml, php7.4-xmlreader, php7.4-xmlwriter, php7.4-mysql, mariadb-server"

    [resources.database]
    type = "mysql"
