#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agendav"
name = "AgenDAV"
description.en = "CalDAV web client"
description.fr = "Client web pour CalDAV"

version = "3.3.1~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
demo = "https://demo.yunohost.org/agendav"
admindoc = "https://agendav.readthedocs.io"
code = "https://github.com/agendav/agendav"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true
sso = true

disk = "10M"
ram.build = "100M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agendav"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de_DE", "en", "es_ES", "fr_FR", "it_IT", "nl_NL"]
    default = "en"

[resources]
    [resources.sources.main]
    url = "https://github.com/agendav/agendav/releases/download/3.3.1/agendav-3.3.1.tar.gz"
    sha256 = "aec1038845ea9b489f575028d092fb7ef3dbee7dcf302783a3f6d383e7473030"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.5-fpm, php8.5-cli, php8.5-ctype, php8.5-curl, php8.5-mbstring, php8.5-xml, php8.5-mysql, php8.5-intl, mariadb-server"

    [resources.database]
    type = "mysql"
