#!/bin/bash

# Source local helpers
source ./_common.sh

# Source app helpers
source /usr/share/yunohost/helpers

# Set app specific variables
app="$YNH_APP_INSTANCE_NAME"
dbname=$app
dbuser=$app

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname"
ynh_mysql_drop_user "$dbuser"

# Retrieve domain from app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete app directory and configurations
rm -rf "/var/www/${app}" "/var/log/${app}"
rm -f "/etc/php5/fpm/pool.d/${app}.conf"
[[ -n $domain ]] && rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

# Reload services
service php5-fpm restart
service nginx reload

# Remove the user account
ynh_system_user_delete "$app"
