#!/bin/bash

# Set app specific variables
app="agendav"
dbname=$app
dbuser=$app

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

# Retrieve domain from app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete app directory and configurations
sudo rm -rf "/var/www/${app}" "/var/log/${app}"
sudo rm -f "/etc/php5/fpm/pool.d/${app}.conf"
[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service php5-fpm restart || true
sudo service nginx reload || true
