#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# GET THE CALDAV APP
#=================================================

caldav_info=$(_ynh_agendav_find_caldav_app)
caldav_app="$(cut -d " " -f 1 <<< "$caldav_info")"
caldav_baseurl="$(cut -d " " -f 2 <<< "$caldav_info")"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep="config/settings.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

mkdir -p "/var/log/$app"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

# Copy and set AgenDAV configuration
timezone=$(timedatectl show --value --property=Timezone)

caldav_domain=$(ynh_app_setting_get --app="$caldav_app" --key=domain)
caldav_path=$(ynh_app_setting_get --app="$caldav_app" --key=path)
caldav_url="https://${caldav_domain}${caldav_path%/}"
caldav_baseurl="${caldav_url}${caldav_baseurl}"

ynh_config_add --template="settings.php" --destination="${install_dir}/web/config/settings.php"

#=================================================
# RUN DATABASE MIGRATIONS (INCLUDES INITIALIZATION)
#=================================================
ynh_script_progression "Upgrading $app..."

(
    cd "$install_dir" || ynh_die
    "php$php_version" agendavcli migrations:migrate --no-interaction
)

# Only agendav user should write here
chown -R "$app" "$install_dir/web/var/cache/"{profiler,twig}

# The agendav user should read here, but does not need to write
# Other users should not be able to read as it stores passwords.
chown -R "$app:www-data" "$install_dir/config/"
chmod -R 750 "$install_dir/config/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
